language: rust

rust:
  - nightly
  - stable

script:
  - cargo build --verbose
  - if [ $TRAVIS_OS_NAME = osx ]; then cargo build --target x86_64-apple-ios --verbose; fi
  - cargo test --verbose

os:
  - linux
  - osx
  - windows