[package]
name = "ai"
version = "0.1.0"
authors = ["linyiyu1992@gmail.com"]
keywords = ["opengl", "cross-platform", "game engine"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/whatever1992/Bzll"

[dependencies]